export enum IncidentTimelineEntryType {
  CHECK_FAILED = 'CHECK_FAILED',
  INCIDENT_STARTED = 'INCIDENT_STARTED',
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  MONITOR_RECOVERED = 'MONITOR_RECOVERED',
  WAITING_FOR_RECOVERY = 'WAITING_FOR_RECOVERY',
  INCIDENT_RESOLVED = 'INCIDENT_RESOLVED',
  INCIDENT_ACKNOWLEDGED = 'INCIDENT_ACKNOWLEDGED',
  COMMENT = 'COMMENT',
}
